// <auto-generated />
using System;
using Company.Delivery.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Company.Delivery.Database.Migrations
{
    [DbContext(typeof(DeliveryDbContext))]
    [Migration("20230327000828_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Company.Delivery.Core.CargoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("WaybillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WaybillId");

                    b.HasIndex(new[] { "Number", "WaybillId" }, "Number_WaybillId_Index")
                        .IsUnique();

                    b.ToTable("CargoItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2936a77a-d491-4cfb-8047-a809acf2ad5e"),
                            Name = "Box",
                            Number = "2023-A-1/01",
                            WaybillId = new Guid("bbb2afb6-8ecf-4f63-9f98-71c3fc1b5f33")
                        },
                        new
                        {
                            Id = new Guid("fea616d3-75b1-49c7-86ce-65107bfe3dfc"),
                            Name = "Pallet",
                            Number = "2023-A-1/02",
                            WaybillId = new Guid("bbb2afb6-8ecf-4f63-9f98-71c3fc1b5f33")
                        });
                });

            modelBuilder.Entity("Company.Delivery.Core.Waybill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Number" }, "Number_Index")
                        .IsUnique();

                    b.ToTable("Waybills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbb2afb6-8ecf-4f63-9f98-71c3fc1b5f33"),
                            Date = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "2023-A-1"
                        });
                });

            modelBuilder.Entity("Company.Delivery.Core.CargoItem", b =>
                {
                    b.HasOne("Company.Delivery.Core.Waybill", "Waybill")
                        .WithMany("Items")
                        .HasForeignKey("WaybillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Waybill");
                });

            modelBuilder.Entity("Company.Delivery.Core.Waybill", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
